### ISSUE TITLE
Theme not applied on Download page 

### ISSUE THREAD

**Issue by koplo199** [dracula/steam#24]
Hi,
It looks like the theme isn't applied on the Download page ?

![Screenshot from 2021-10-01 19-20-35](https://user-images.githubusercontent.com/85577251/135662029-d76b8506-a0d7-453c-b3c7-4d2d3a8db086.png)

**Comment by tintinmaster** [comment]
Steam changed the Layout of the Download page in September, I have to look at it, if we can change the look of the new one. But Steam makes it harder every update to apply custom themes.

**Comment by koplo199** [comment]
If that could help here is the css for changing the background of the page and the color of the blue separator : 
```css
/* Downloads */
.downloads_DownloadsPage_1bq4x {
    background-image: linear-gradient(to bottom, var(--draculaBG) 0%, var(--draculaBG) 100%);
}

.downloads_TopBar_SEmVp {
    background: linear-gradient(to right, var(--draculaCFAccent) 0%, var(--draculaCFAccent) 100%);
}

```
